version: '3'

services:

  # postgresql container
  db_postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_volumen:/var/lib/postgresql/data
    restart: always
    networks:
      - type_figth_network

  # pgadmin container
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db_postgres
    networks:
      - type_figth_network

  # mysql container
  db_mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_volumen:/var/lib/mysql
    networks:
      - type_figth_network

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db_mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - type_figth_network

volumes:
  db_volumen:

networks:
  type_figth_network:
    driver: bridge