server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=2

        - id: MATCH-SERVICE
          uri: lb://MATCH-SERVICE
          predicates:
            - Path=/api/v1/match/**
          filters:
            - StripPrefix=2

        - id: QUOTE-SERVICE
          uri: lb://QUOTE-SERVICE
          predicates:
            - Path=/api/v1/quote/**
          filters:
            - StripPrefix=2

        - id: DISCOVERY-SERVICE
          uri: http://localhost:8761
          predicates:
            - Path=/discovery/web
          filters:
            - SetPath=/

        - id: DISCOVERY-SERVICE-STATIC
          uri: http://localhost:8761
          predicates:
            - Path=/discovery/**
          filters:
            - SetPath=/

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    root: INFO

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/