server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:4200, http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: MATCH-SERVICE
          uri: lb://MATCH-SERVICE
          predicates:
            - Path=/api/v1/match/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: QUOTE-SERVICE
          uri: lb://QUOTE-SERVICE
          predicates:
            - Path=/api/v1/quote/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: CREDENTIALS-SERVICE
          uri: lb://credentials-api
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        - id: DISCOVERY-SERVICE
          uri: http://localhost:8761
          predicates:
            - Path=/discovery/web
          filters:
            - SetPath=/
            - AuthFilter

        - id: DISCOVERY-SERVICE-STATIC
          uri: http://localhost:8761
          predicates:
            - Path=/discovery/**
          filters:
            - SetPath=/
            - AuthFilter

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    root: INFO

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/