server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**

        - id: MATCH-SERVICE
          uri: lb://MATCH-SERVICE
          predicates:
            - Path=/api/v1/match/**

  application:
    name: API-GATEWAY

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
